name: deploy main

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: build
      run: |
        wget https://poggit.pmmp.io/r/149344/PocketMine-DevTools.phar -O DevTools.phar
        mkdir build
        php -d phar.readonly=0 DevTools.phar --make ./ --out ./build/BBLifeCore.phar
        
    - name: deploy
      uses: sand4rt/ftp-deployer@v1.3
      with:
        sftp: true
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT}}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        remote_folder: ${{ secrets.REMOTE_FOLDER_MAIN }}
        local_folder: ./build/
        cleanup: false
